### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by Veight** [phanx-wow/PhanxChat#15]
Is this a possible feature we could get?

**Comment by Phanx** [comment]
Nope. I hate chat timestamps, and will never add any features related to 
them in any addon I write or maintain.

That said, the default UI option to enable chat timestamps should work; 
PhanxChat doesn't intentionally do anything to remove them if they're 
present from some other source.

**Comment by Veight** [comment]
Thanks. I wasn't aware. Will do that then instead.

**Comment by Phanx** [comment]
Feel free to reopen the issue if PhanxChat causes any issues with the default UI's timestamps.
