### ISSUE TITLE
LUA error when changing settings

### ISSUE THREAD

**Issue by AL3x3y0** [phanx-wow/PhanxChat#18]
After changing any checkbox in settings I got this:

Message: ...t\Libs\PhanxConfig-Checkbox\PhanxConfig-Checkbox.lua:30: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Time: 09/06/17 00:21:26
Count: 1
Stack: ...t\Libs\PhanxConfig-Checkbox\PhanxConfig-Checkbox.lua:30: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
[C]: ?
[C]: in function `PlaySound'
...t\Libs\PhanxConfig-Checkbox\PhanxConfig-Checkbox.lua:30: in function <...t\Libs\PhanxConfig-Checkbox\PhanxConfig-Checkbox.lua:28>

And now I can't change "Sticky chat" and "Shorten real names" options.

**Comment by Kkthnx** [comment]
For the time being until @Phanx can look into this issue. Please use this addon which should adjust the issue at the moment.

https://mods.curse.com/addons/wow/276930-playsoundfix

**Comment by AL3x3y0** [comment]
@Phanx, will you update your addon?

**Comment by Phanx** [comment]
Fixed
