### ISSUE TITLE
💀

### ISSUE THREAD

**Issue by AL3x3y0** [phanx-wow/PhanxChat#19]

**Comment by armordecai** [comment]
I can't reproduce this. For me, the edit box accepts a maximum of 255 characters, and sends them with no problem.

- What language are you playing WoW in?
- Do you still get the error when PhanxChat is the only addon enabled?

**Comment by AL3x3y0** [comment]
> What language are you playing WoW in?

I'm get that error on en-gb, but now I'm transfered to russian realm and still getting it:
![image](https://user-images.githubusercontent.com/29476322/30730987-c2b666ee-9f7b-11e7-889c-975924ef47d4.png)

> Do you still get the error when PhanxChat is the only addon enabled?

Yes.

> Can you copy and paste the exact text of a message you can send that gives the error?

Now I realized that the error only occurs when the text is a cyrillic, for example:

`ыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыы`
There is 256 symbols, and if I type all letters in english, for example:
`AsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsdasdAsd`
There is 255 symbols and no error.
